import type { Metadata } from "next";
import {
	Geist,
	Geist_Mono,
	Inter,
	Noto_Sans,
	Noto_Serif_Display,
} from "next/font/google";
import "./globals.css";
import RootProvider from "@/lib/providers/RootProvider";
import DevComponents from "@/features/dev/fixed/DevComponents";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const notoSans = Noto_Sans({
	variable: "--font-noto-sans",
	subsets: ["latin"],
});

const notoSerifDisplay = Noto_Serif_Display({
	variable: "--font-noto-serif-display",
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-theme="dark">
			<body
				className={`${inter.variable} ${notoSans.variable} ${notoSerifDisplay.variable} antialiased  font-inter w-screen overflow-x-hidden dark:bg-black`}>
				<RootProvider>{children}</RootProvider>
				<DevComponents />
			</body>
		</html>
	);
}
